version: "{build}"

environment:
  matrix:
  - ARCHITECTURE: x64
    MSVC_VER: 14
  - ARCHITECTURE: x86
    MSVC_VER: 14
  - ARCHITECTURE: x64
    MSVC_VER: 12
  - ARCHITECTURE: x86
    MSVC_VER: 12

branches:
  except:
    - /^(wip\/)?(travis|osx|mingw|ipp)(\-.+)?$/

configuration: Debug

install:
  - git submodule update --init --recursive

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio %MSVC_VER%.0\VC\vcvarsall.bat" %ARCHITECTURE%

build_script: cl.exe /Fetest munit\munit.c test.c

test_script: test.exe --color always
